[package]
name = "mk2apc_4light"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.9.1"
wmidi = "4.0.6"
config = "0.13.3"
derive = "1.0.0"